version: '3'

services:
  rdb: # 3306
    build:
      context: .
      dockerfile: ./rdb/Dockerfile
    container_name: mysqldb
    volumes:
      - ./rdb/data:/var/lib/mysql
      - ./rdb/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./rdb/db/sql/:/docker-entrypoint-initdb.d/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks: 
      - backend_network
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: appserver
    depends_on:
      - rdb
    ports: 
      - 8080:3000
    volumes:
      - ./server:/opt/application # work dir
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: bash -c "carton install && carton exec -- ./script/application prefork"
    networks:
      - backend_network
      - application_network
  front:
    image: nginx
    container_name: webfront
    depends_on:
      - server
    ports: 
      - 8081:80
    volumes: 
      - ./front/app/dst:/usr/share/nginx/html
      - ./front/nginx/conf.d:/etc/nginx/conf.d
    networks: 
      - application_network

networks:
  backend_network:
    driver: bridge
  application_network:
    driver: bridge


