# Application Framework
requires "Mojo";
requires "Mojo::File";
requires "Mojolicious::Routes";

# DB Connector
requires "Mojo::mysql";

# OOP
requires "Mouse";

# Test
requires "Test::More";
requires "Test::Mojo";

# Utilities
requires "List::Util";
requires "Data::Printer";